# -*- coding: utf-8 -*-
"""scrapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OM1GHcvWZ4xhOXnrL5Og3b_pJlRDkfN
"""

!pip install google_play_scraper

from google_play_scraper import Sort, reviews
import pandas as pd

app_id = 'jp.pokemon.pokemonunite'
all_reviews = []
target_reviews = 50000

sort_options = [Sort.NEWEST, Sort.MOST_RELEVANT, Sort.RATING]

for sort_option in sort_options:
    continuation_token = None
    while len(all_reviews) < target_reviews:
        result, continuation_token = reviews(
            app_id,
            lang='id',
            country='id',
            sort=sort_option,
            count=200,
            continuation_token=continuation_token
        )
        all_reviews.extend(result)
        if not continuation_token:
            break
        print(f"Sudah mengambil {len(all_reviews)} ulasan dengan {sort_option}...")

    if len(all_reviews) >= target_reviews:
        break

all_reviews = all_reviews[:target_reviews]

df = pd.DataFrame(all_reviews)
df.to_csv('reviews.csv', index=False)
print(f"Selesai! Total {len(all_reviews)} ulasan disimpan.")